title: JebrAI
description: Described as
baseurl: ""
url: "https://yourusername.github.io"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
